# Generated by Django 6.1.1 on 2026-09-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVPResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Аты-жөні')),
                ('attendance', models.CharField(choices=[('yes', 'Бәрі дайын'), ('maybe', 'Мүмкін'), ('no', 'Қатыспаймын')], max_length=10, verbose_name='Қатысуым')),
                ('guest_count', models.PositiveIntegerField(default=1, verbose_name='Қонақтар саны')),
                ('notes', models.TextField(blank=True, verbose_name='Қосымша ақпарат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
