# Generated by Django 6.1.1 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvpresponse',
            name='attendance',
            field=models.CharField(
                choices=[
                    ('yes', 'Иә, әрине'),
                    ('maybe', 'Жұбайыммен келемін'),
                    ('no', 'Келе алмаймын'),
                ],
                max_length=10,
                verbose_name='Қатысуым',
            ),
        ),
    ]
